
services:
  fuseki:
    image: stain/jena-fuseki
    container_name: fuseki
    ports:
      - "3030:3030"
    volumes:
      - fuseki_data:/fuseki
      - ./ServiceConfig/fuseki/tdb2-dataset.ttl:/fuseki/config.ttl
      - ./ServiceConfig/fuseki/tdb2data:/fuseki/DB
      - ./ServiceConfig/fuseki/shiro.ini:/fuseki/shiro.ini
    networks:
      - vds_network
    environment:
      - FUSEKI_CONFIG=/fuseki/config.ttl
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3030/$/ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  gutenberggraphbuilder:
    build:
      context: .
      dockerfile: Src/GutenbergGraphBuilder/Dockerfile
    container_name: gutenberggraphbuilder
    depends_on:
      fuseki:
        condition: service_healthy
    networks:
      - vds_network
    environment:
      - FUSEKI_URL=http://fuseki:3030/dataset
      - FUSEKI_UPDATE_URL=http://fuseki:3030/dataset/update
      - FUSEKI_QUERY_URL=http://fuseki:3030/dataset/query
      - FUSEKI_USERNAME=${FUSEKI_USERNAME}
      - FUSEKI_PASSWORD=${FUSEKI_PASSWORD}

volumes:
  fuseki_data: {}

networks:
  vds_network: {}
